// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: proto/aero.proto

package aero

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamType int32

const (
	StreamType_CONTROL StreamType = 0
	StreamType_GENERAL StreamType = 1
	StreamType_UDP     StreamType = 2
	StreamType_AI      StreamType = 3
	StreamType_BROWSER StreamType = 4
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "CONTROL",
		1: "GENERAL",
		2: "UDP",
		3: "AI",
		4: "BROWSER",
	}
	StreamType_value = map[string]int32{
		"CONTROL": 0,
		"GENERAL": 1,
		"UDP":     2,
		"AI":      3,
		"BROWSER": 4,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aero_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_proto_aero_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{0}
}

type SchedulerCommand_CommandType int32

const (
	SchedulerCommand_KEEP        SchedulerCommand_CommandType = 0
	SchedulerCommand_SWITCH_PATH SchedulerCommand_CommandType = 1
	SchedulerCommand_SWITCH_NODE SchedulerCommand_CommandType = 2
	SchedulerCommand_DEGRADE     SchedulerCommand_CommandType = 3
)

// Enum value maps for SchedulerCommand_CommandType.
var (
	SchedulerCommand_CommandType_name = map[int32]string{
		0: "KEEP",
		1: "SWITCH_PATH",
		2: "SWITCH_NODE",
		3: "DEGRADE",
	}
	SchedulerCommand_CommandType_value = map[string]int32{
		"KEEP":        0,
		"SWITCH_PATH": 1,
		"SWITCH_NODE": 2,
		"DEGRADE":     3,
	}
)

func (x SchedulerCommand_CommandType) Enum() *SchedulerCommand_CommandType {
	p := new(SchedulerCommand_CommandType)
	*p = x
	return p
}

func (x SchedulerCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aero_proto_enumTypes[1].Descriptor()
}

func (SchedulerCommand_CommandType) Type() protoreflect.EnumType {
	return &file_proto_aero_proto_enumTypes[1]
}

func (x SchedulerCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerCommand_CommandType.Descriptor instead.
func (SchedulerCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{10, 0}
}

type ConnectRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`      // "aero/2.0"
	Token     string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`          // Bearer token
	Nonce     []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`          // 32 字节随机数
	Timestamp uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 毫秒
	Streams   []*StreamSpec          `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	// Phase 4: 运营商自适应
	IspHint       string   `protobuf:"bytes,6,opt,name=isp_hint,json=ispHint,proto3" json:"isp_hint,omitempty"` // "china_telecom" / "china_unicom" / "china_mobile"
	TestedPorts   []uint32 `protobuf:"varint,7,rep,packed,name=tested_ports,json=testedPorts,proto3" json:"tested_ports,omitempty"`
	UdpAvailable  bool     `protobuf:"varint,8,opt,name=udp_available,json=udpAvailable,proto3" json:"udp_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_aero_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ConnectRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectRequest) GetStreams() []*StreamSpec {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *ConnectRequest) GetIspHint() string {
	if x != nil {
		return x.IspHint
	}
	return ""
}

func (x *ConnectRequest) GetTestedPorts() []uint32 {
	if x != nil {
		return x.TestedPorts
	}
	return nil
}

func (x *ConnectRequest) GetUdpAvailable() bool {
	if x != nil {
		return x.UdpAvailable
	}
	return false
}

type ConnectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accepted          bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                          // UUID
	HeartbeatInterval uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // 秒，默认 30
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ServerParams      map[string]string      `protobuf:"bytes,5,rep,name=server_params,json=serverParams,proto3" json:"server_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Phase 4: 服务端推荐
	RecommendedProtocol string `protobuf:"bytes,6,opt,name=recommended_protocol,json=recommendedProtocol,proto3" json:"recommended_protocol,omitempty"` // "quic" / "tcp_h2" / "tcp_ws"
	RecommendedPort     uint32 `protobuf:"varint,7,opt,name=recommended_port,json=recommendedPort,proto3" json:"recommended_port,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_aero_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetHeartbeatInterval() uint32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetServerParams() map[string]string {
	if x != nil {
		return x.ServerParams
	}
	return nil
}

func (x *ConnectResponse) GetRecommendedProtocol() string {
	if x != nil {
		return x.RecommendedProtocol
	}
	return ""
}

func (x *ConnectResponse) GetRecommendedPort() uint32 {
	if x != nil {
		return x.RecommendedPort
	}
	return 0
}

type StreamSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamType    StreamType             `protobuf:"varint,2,opt,name=stream_type,json=streamType,proto3,enum=aero.StreamType" json:"stream_type,omitempty"`
	TargetHost    string                 `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSpec) Reset() {
	*x = StreamSpec{}
	mi := &file_proto_aero_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSpec) ProtoMessage() {}

func (x *StreamSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSpec.ProtoReflect.Descriptor instead.
func (*StreamSpec) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{2}
}

func (x *StreamSpec) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamSpec) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_CONTROL
}

func (x *StreamSpec) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *StreamSpec) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

// Stream 数据帧
type TcpFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpFrame) Reset() {
	*x = TcpFrame{}
	mi := &file_proto_aero_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpFrame) ProtoMessage() {}

func (x *TcpFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpFrame.ProtoReflect.Descriptor instead.
func (*TcpFrame) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{3}
}

func (x *TcpFrame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *TcpFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TcpFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type UdpFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SrcAddr       string                 `protobuf:"bytes,3,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpFrame) Reset() {
	*x = UdpFrame{}
	mi := &file_proto_aero_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpFrame) ProtoMessage() {}

func (x *UdpFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpFrame.ProtoReflect.Descriptor instead.
func (*UdpFrame) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{4}
}

func (x *UdpFrame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *UdpFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UdpFrame) GetSrcAddr() string {
	if x != nil {
		return x.SrcAddr
	}
	return ""
}

type AiStreamHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // "gpt-4", "claude-3" 等
	ContextId     string                 `protobuf:"bytes,3,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // 断线续传标识
	Resume        bool                   `protobuf:"varint,4,opt,name=resume,proto3" json:"resume,omitempty"`                       // 是否续传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiStreamHeader) Reset() {
	*x = AiStreamHeader{}
	mi := &file_proto_aero_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiStreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiStreamHeader) ProtoMessage() {}

func (x *AiStreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiStreamHeader.ProtoReflect.Descriptor instead.
func (*AiStreamHeader) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{5}
}

func (x *AiStreamHeader) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *AiStreamHeader) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AiStreamHeader) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *AiStreamHeader) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

type AiStreamFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	IsToken       bool                   `protobuf:"varint,3,opt,name=is_token,json=isToken,proto3" json:"is_token,omitempty"`             // 是否为 token 边界
	TokenIndex    uint32                 `protobuf:"varint,4,opt,name=token_index,json=tokenIndex,proto3" json:"token_index,omitempty"`    // token 序号
	TimestampUs   uint64                 `protobuf:"varint,5,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"` // 发送时间戳（微秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiStreamFrame) Reset() {
	*x = AiStreamFrame{}
	mi := &file_proto_aero_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiStreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiStreamFrame) ProtoMessage() {}

func (x *AiStreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiStreamFrame.ProtoReflect.Descriptor instead.
func (*AiStreamFrame) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{6}
}

func (x *AiStreamFrame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *AiStreamFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AiStreamFrame) GetIsToken() bool {
	if x != nil {
		return x.IsToken
	}
	return false
}

func (x *AiStreamFrame) GetTokenIndex() uint32 {
	if x != nil {
		return x.TokenIndex
	}
	return 0
}

func (x *AiStreamFrame) GetTimestampUs() uint64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_aero_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_aero_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatAck) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type MetricsReport struct {
	state     protoimpl.MessageState         `protogen:"open.v1"`
	SessionId string                         `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp uint64                         `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Streams   []*MetricsReport_StreamMetrics `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	// AI 指标
	AiFirstTokenLatencyMs uint64 `protobuf:"varint,4,opt,name=ai_first_token_latency_ms,json=aiFirstTokenLatencyMs,proto3" json:"ai_first_token_latency_ms,omitempty"`
	AiAvgTokenIntervalMs  uint64 `protobuf:"varint,5,opt,name=ai_avg_token_interval_ms,json=aiAvgTokenIntervalMs,proto3" json:"ai_avg_token_interval_ms,omitempty"`
	AiTokensTotal         uint32 `protobuf:"varint,6,opt,name=ai_tokens_total,json=aiTokensTotal,proto3" json:"ai_tokens_total,omitempty"`
	// 网络质量
	RttMs         uint32  `protobuf:"varint,7,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	JitterMs      uint32  `protobuf:"varint,8,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	LossRate      float32 `protobuf:"fixed32,9,opt,name=loss_rate,json=lossRate,proto3" json:"loss_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_proto_aero_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetStreams() []*MetricsReport_StreamMetrics {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *MetricsReport) GetAiFirstTokenLatencyMs() uint64 {
	if x != nil {
		return x.AiFirstTokenLatencyMs
	}
	return 0
}

func (x *MetricsReport) GetAiAvgTokenIntervalMs() uint64 {
	if x != nil {
		return x.AiAvgTokenIntervalMs
	}
	return 0
}

func (x *MetricsReport) GetAiTokensTotal() uint32 {
	if x != nil {
		return x.AiTokensTotal
	}
	return 0
}

func (x *MetricsReport) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *MetricsReport) GetJitterMs() uint32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *MetricsReport) GetLossRate() float32 {
	if x != nil {
		return x.LossRate
	}
	return 0
}

type SchedulerCommand struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          SchedulerCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=aero.SchedulerCommand_CommandType" json:"type,omitempty"`
	TargetAddr    string                       `protobuf:"bytes,2,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`
	Protocol      string                       `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Params        map[string]string            `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerCommand) Reset() {
	*x = SchedulerCommand{}
	mi := &file_proto_aero_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerCommand) ProtoMessage() {}

func (x *SchedulerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerCommand.ProtoReflect.Descriptor instead.
func (*SchedulerCommand) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{10}
}

func (x *SchedulerCommand) GetType() SchedulerCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return SchedulerCommand_KEEP
}

func (x *SchedulerCommand) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *SchedulerCommand) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SchedulerCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type TunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetHost    string                 `protobuf:"bytes,1,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp_h2" / "quic" / "tcp_ws"
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRequest) Reset() {
	*x = TunnelRequest{}
	mi := &file_proto_aero_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest) ProtoMessage() {}

func (x *TunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest.ProtoReflect.Descriptor instead.
func (*TunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{11}
}

func (x *TunnelRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *TunnelRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TunnelRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TunnelRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type TunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelResponse) Reset() {
	*x = TunnelResponse{}
	mi := &file_proto_aero_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse) ProtoMessage() {}

func (x *TunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse.ProtoReflect.Descriptor instead.
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{12}
}

func (x *TunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TunnelResponse) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *TunnelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProbeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []string               `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"` // ["udp:443", "tcp:443", "tcp:8443"]
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Parallel      uint32                 `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeConfig) Reset() {
	*x = ProbeConfig{}
	mi := &file_proto_aero_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfig) ProtoMessage() {}

func (x *ProbeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfig.ProtoReflect.Descriptor instead.
func (*ProbeConfig) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{13}
}

func (x *ProbeConfig) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ProbeConfig) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ProbeConfig) GetParallel() uint32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

type ProbeResult struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*ProbeResult_PathResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Recommended   string                    `protobuf:"bytes,2,opt,name=recommended,proto3" json:"recommended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_proto_aero_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{14}
}

func (x *ProbeResult) GetResults() []*ProbeResult_PathResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ProbeResult) GetRecommended() string {
	if x != nil {
		return x.Recommended
	}
	return ""
}

type PathSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPath   string                 `protobuf:"bytes,1,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextId     string                 `protobuf:"bytes,4,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSwitchRequest) Reset() {
	*x = PathSwitchRequest{}
	mi := &file_proto_aero_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSwitchRequest) ProtoMessage() {}

func (x *PathSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSwitchRequest.ProtoReflect.Descriptor instead.
func (*PathSwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{15}
}

func (x *PathSwitchRequest) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *PathSwitchRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *PathSwitchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PathSwitchRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

type PathSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSwitchResponse) Reset() {
	*x = PathSwitchResponse{}
	mi := &file_proto_aero_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSwitchResponse) ProtoMessage() {}

func (x *PathSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSwitchResponse.ProtoReflect.Descriptor instead.
func (*PathSwitchResponse) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{16}
}

func (x *PathSwitchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PathSwitchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Stream 流量统计
type MetricsReport_StreamMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamType    StreamType             `protobuf:"varint,2,opt,name=stream_type,json=streamType,proto3,enum=aero.StreamType" json:"stream_type,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,3,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,4,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,5,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,6,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport_StreamMetrics) Reset() {
	*x = MetricsReport_StreamMetrics{}
	mi := &file_proto_aero_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport_StreamMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport_StreamMetrics) ProtoMessage() {}

func (x *MetricsReport_StreamMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport_StreamMetrics.ProtoReflect.Descriptor instead.
func (*MetricsReport_StreamMetrics) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{9, 0}
}

func (x *MetricsReport_StreamMetrics) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MetricsReport_StreamMetrics) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_CONTROL
}

func (x *MetricsReport_StreamMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *MetricsReport_StreamMetrics) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *MetricsReport_StreamMetrics) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *MetricsReport_StreamMetrics) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

type ProbeResult_PathResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	RttMs         uint32                 `protobuf:"varint,3,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	Reachable     bool                   `protobuf:"varint,4,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LossRate      float32                `protobuf:"fixed32,5,opt,name=loss_rate,json=lossRate,proto3" json:"loss_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult_PathResult) Reset() {
	*x = ProbeResult_PathResult{}
	mi := &file_proto_aero_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult_PathResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult_PathResult) ProtoMessage() {}

func (x *ProbeResult_PathResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aero_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult_PathResult.ProtoReflect.Descriptor instead.
func (*ProbeResult_PathResult) Descriptor() ([]byte, []int) {
	return file_proto_aero_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ProbeResult_PathResult) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProbeResult_PathResult) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ProbeResult_PathResult) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *ProbeResult_PathResult) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *ProbeResult_PathResult) GetLossRate() float32 {
	if x != nil {
		return x.LossRate
	}
	return 0
}

var File_proto_aero_proto protoreflect.FileDescriptor

const file_proto_aero_proto_rawDesc = "" +
	"\n" +
	"\x10proto/aero.proto\x12\x04aero\"\x83\x02\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12*\n" +
	"\astreams\x18\x05 \x03(\v2\x10.aero.StreamSpecR\astreams\x12\x19\n" +
	"\bisp_hint\x18\x06 \x01(\tR\aispHint\x12!\n" +
	"\ftested_ports\x18\a \x03(\rR\vtestedPorts\x12#\n" +
	"\rudp_available\x18\b \x01(\bR\fudpAvailable\"\x82\x03\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12-\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\rR\x11heartbeatInterval\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12L\n" +
	"\rserver_params\x18\x05 \x03(\v2'.aero.ConnectResponse.ServerParamsEntryR\fserverParams\x121\n" +
	"\x14recommended_protocol\x18\x06 \x01(\tR\x13recommendedProtocol\x12)\n" +
	"\x10recommended_port\x18\a \x01(\rR\x0frecommendedPort\x1a?\n" +
	"\x11ServerParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\n" +
	"StreamSpec\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x121\n" +
	"\vstream_type\x18\x02 \x01(\x0e2\x10.aero.StreamTypeR\n" +
	"streamType\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\rR\n" +
	"targetPort\"]\n" +
	"\bTcpFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\\\n" +
	"\bUdpFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\bsrc_addr\x18\x03 \x01(\tR\asrcAddr\"\x83\x01\n" +
	"\x0eAiStreamHeader\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"context_id\x18\x03 \x01(\tR\tcontextId\x12\x16\n" +
	"\x06resume\x18\x04 \x01(\bR\x06resume\"\xa5\x01\n" +
	"\rAiStreamFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\bis_token\x18\x03 \x01(\bR\aisToken\x12\x1f\n" +
	"\vtoken_index\x18\x04 \x01(\rR\n" +
	"tokenIndex\x12!\n" +
	"\ftimestamp_us\x18\x05 \x01(\x04R\vtimestampUs\"E\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\"H\n" +
	"\fHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\"\xda\x04\n" +
	"\rMetricsReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12;\n" +
	"\astreams\x18\x03 \x03(\v2!.aero.MetricsReport.StreamMetricsR\astreams\x128\n" +
	"\x19ai_first_token_latency_ms\x18\x04 \x01(\x04R\x15aiFirstTokenLatencyMs\x126\n" +
	"\x18ai_avg_token_interval_ms\x18\x05 \x01(\x04R\x14aiAvgTokenIntervalMs\x12&\n" +
	"\x0fai_tokens_total\x18\x06 \x01(\rR\raiTokensTotal\x12\x15\n" +
	"\x06rtt_ms\x18\a \x01(\rR\x05rttMs\x12\x1b\n" +
	"\tjitter_ms\x18\b \x01(\rR\bjitterMs\x12\x1b\n" +
	"\tloss_rate\x18\t \x01(\x02R\blossRate\x1a\xe3\x01\n" +
	"\rStreamMetrics\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x121\n" +
	"\vstream_type\x18\x02 \x01(\x0e2\x10.aero.StreamTypeR\n" +
	"streamType\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x03 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x04 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x05 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x06 \x01(\x04R\vpacketsRecv\"\xc6\x02\n" +
	"\x10SchedulerCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".aero.SchedulerCommand.CommandTypeR\x04type\x12\x1f\n" +
	"\vtarget_addr\x18\x02 \x01(\tR\n" +
	"targetAddr\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12:\n" +
	"\x06params\x18\x04 \x03(\v2\".aero.SchedulerCommand.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\vCommandType\x12\b\n" +
	"\x04KEEP\x10\x00\x12\x0f\n" +
	"\vSWITCH_PATH\x10\x01\x12\x0f\n" +
	"\vSWITCH_NODE\x10\x02\x12\v\n" +
	"\aDEGRADE\x10\x03\"\xe5\x01\n" +
	"\rTunnelRequest\x12\x1f\n" +
	"\vtarget_host\x18\x01 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12:\n" +
	"\aoptions\x18\x04 \x03(\v2 .aero.TunnelRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x0eTunnelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"b\n" +
	"\vProbeConfig\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\rR\bparallel\"\xf8\x01\n" +
	"\vProbeResult\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.aero.ProbeResult.PathResultR\aresults\x12 \n" +
	"\vrecommended\x18\x02 \x01(\tR\vrecommended\x1a\x8e\x01\n" +
	"\n" +
	"PathResult\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x15\n" +
	"\x06rtt_ms\x18\x03 \x01(\rR\x05rttMs\x12\x1c\n" +
	"\treachable\x18\x04 \x01(\bR\treachable\x12\x1b\n" +
	"\tloss_rate\x18\x05 \x01(\x02R\blossRate\"\x8f\x01\n" +
	"\x11PathSwitchRequest\x12!\n" +
	"\fcurrent_path\x18\x01 \x01(\tR\vcurrentPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x04 \x01(\tR\tcontextId\"J\n" +
	"\x12PathSwitchResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*D\n" +
	"\n" +
	"StreamType\x12\v\n" +
	"\aCONTROL\x10\x00\x12\v\n" +
	"\aGENERAL\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\x06\n" +
	"\x02AI\x10\x03\x12\v\n" +
	"\aBROWSER\x10\x04B%Z#github.com/aero-protocol/proto/aerob\x06proto3"

var (
	file_proto_aero_proto_rawDescOnce sync.Once
	file_proto_aero_proto_rawDescData []byte
)

func file_proto_aero_proto_rawDescGZIP() []byte {
	file_proto_aero_proto_rawDescOnce.Do(func() {
		file_proto_aero_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aero_proto_rawDesc), len(file_proto_aero_proto_rawDesc)))
	})
	return file_proto_aero_proto_rawDescData
}

var file_proto_aero_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_aero_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_aero_proto_goTypes = []any{
	(StreamType)(0),                     // 0: aero.StreamType
	(SchedulerCommand_CommandType)(0),   // 1: aero.SchedulerCommand.CommandType
	(*ConnectRequest)(nil),              // 2: aero.ConnectRequest
	(*ConnectResponse)(nil),             // 3: aero.ConnectResponse
	(*StreamSpec)(nil),                  // 4: aero.StreamSpec
	(*TcpFrame)(nil),                    // 5: aero.TcpFrame
	(*UdpFrame)(nil),                    // 6: aero.UdpFrame
	(*AiStreamHeader)(nil),              // 7: aero.AiStreamHeader
	(*AiStreamFrame)(nil),               // 8: aero.AiStreamFrame
	(*Heartbeat)(nil),                   // 9: aero.Heartbeat
	(*HeartbeatAck)(nil),                // 10: aero.HeartbeatAck
	(*MetricsReport)(nil),               // 11: aero.MetricsReport
	(*SchedulerCommand)(nil),            // 12: aero.SchedulerCommand
	(*TunnelRequest)(nil),               // 13: aero.TunnelRequest
	(*TunnelResponse)(nil),              // 14: aero.TunnelResponse
	(*ProbeConfig)(nil),                 // 15: aero.ProbeConfig
	(*ProbeResult)(nil),                 // 16: aero.ProbeResult
	(*PathSwitchRequest)(nil),           // 17: aero.PathSwitchRequest
	(*PathSwitchResponse)(nil),          // 18: aero.PathSwitchResponse
	nil,                                 // 19: aero.ConnectResponse.ServerParamsEntry
	(*MetricsReport_StreamMetrics)(nil), // 20: aero.MetricsReport.StreamMetrics
	nil,                                 // 21: aero.SchedulerCommand.ParamsEntry
	nil,                                 // 22: aero.TunnelRequest.OptionsEntry
	(*ProbeResult_PathResult)(nil),      // 23: aero.ProbeResult.PathResult
}
var file_proto_aero_proto_depIdxs = []int32{
	4,  // 0: aero.ConnectRequest.streams:type_name -> aero.StreamSpec
	19, // 1: aero.ConnectResponse.server_params:type_name -> aero.ConnectResponse.ServerParamsEntry
	0,  // 2: aero.StreamSpec.stream_type:type_name -> aero.StreamType
	20, // 3: aero.MetricsReport.streams:type_name -> aero.MetricsReport.StreamMetrics
	1,  // 4: aero.SchedulerCommand.type:type_name -> aero.SchedulerCommand.CommandType
	21, // 5: aero.SchedulerCommand.params:type_name -> aero.SchedulerCommand.ParamsEntry
	22, // 6: aero.TunnelRequest.options:type_name -> aero.TunnelRequest.OptionsEntry
	23, // 7: aero.ProbeResult.results:type_name -> aero.ProbeResult.PathResult
	0,  // 8: aero.MetricsReport.StreamMetrics.stream_type:type_name -> aero.StreamType
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_aero_proto_init() }
func file_proto_aero_proto_init() {
	if File_proto_aero_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aero_proto_rawDesc), len(file_proto_aero_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_aero_proto_goTypes,
		DependencyIndexes: file_proto_aero_proto_depIdxs,
		EnumInfos:         file_proto_aero_proto_enumTypes,
		MessageInfos:      file_proto_aero_proto_msgTypes,
	}.Build()
	File_proto_aero_proto = out.File
	file_proto_aero_proto_goTypes = nil
	file_proto_aero_proto_depIdxs = nil
}
